name: CI with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
    
      - name: Run unit tests
        run: |
            go test ./internal/server 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build services with Docker Compose plugin
        run: |
          docker compose build

      - name: Start services
        run: |
          docker compose up -d db
          until docker compose exec db pg_isready -U weather; do
            echo "Waiting for PostgreSQL...";
          done
          docker compose up -d app
      
      - name: Mock Automation Tests Run
        run: | 
            echo "----------------"
            echo "All Tests Passe."
            echo "----------------"
      
      - name: Deployment Mock
        run: |
            echo "Starting deploy"
            echo "Deployed"

      - name: Tear down services
        if: always()
        run: |
          docker compose down --volumes